### ISSUE TITLE
Expose information about publisher presence from the subscriber SDK

### ISSUE THREAD

**Issue by KacperKluka** [ably/ably-asset-tracking-swift#368]
The subscriber API should expose the information whether the publisher is present in the channel or not. 

Android PR for reference: https://github.com/ably/ably-asset-tracking-android/pull/754

┆Issue is synchronized with this [Jira Uncategorised](https://ably.atlassian.net/browse/SDK-2648) by [Unito](https://www.unito.io)

**Comment by lawrence-forooghian** [comment]
@KacperKluka I'm going to start implementing this but I'm a little bit confused about the motivation behind this new API. Would you mind explaining what kind of use case we have in mind for it, and when somebody might wish to use it instead of the existing `Subscriber.trackableStates` API? I'm particularly confused since the video on https://github.com/ably/ably-asset-tracking-android/pull/754 always shows the trackable state label and the presence label as showing the same value.

**Comment by KacperKluka** [comment]
It was added in order to enable customers to detect when the publisher is present. They might want to know that because if the publisher is not present they could use some other tracking solutions or perform other fallback logic. 
I agree that at the moment the same information could be inferred from the `TrackableState` object, however, the logic behind `TrackableState` might change in the future so having this option in the API doesn't seem like a bad idea.
