### ISSUE TITLE
When using animation, the asset position on map quickly drifts far from received asset positions

### ISSUE THREAD

**Issue by lawrence-forooghian** [ably/ably-asset-tracking-swift#375]
Whilst investigating #369 I needed to test out the current behaviour of the location animations. I was surprised to find that the position displayed on the subscriber’s map quickly drifts very far from the published positions that it receives.

The full data and methodology is at https://github.com/ably/ably-asset-tracking-swift/compare/main...369-investigate-animation-location-drift, but a graph sums it up well. It shows that, when the publisher is driving down a road, after 140 seconds the map position displayed by the subscriber is around 2km away from the last published location that it received.

![animation-drift](https://user-images.githubusercontent.com/53756884/191769292-d2f50dbe-d53f-4f44-94df-907440d8c078.svg)

This doesn't seem like an intentional behaviour to me. @KacperKluka is this how the Android one behaves?

┆Issue is synchronized with this [Jira Uncategorised](https://ably.atlassian.net/browse/SDK-2657) by [Unito](https://www.unito.io)

**Comment by KacperKluka** [comment]
On Android we have a constant amount of time for the whole animation that's calculated [here](https://github.com/ably/ably-asset-tracking-android/blob/main/ui-sdk/src/main/java/com/ably/tracking/ui/animation/CoreLocationAnimator.kt#L88-L89). Then we take that time, [divide it](https://github.com/ably/ably-asset-tracking-android/blob/main/ui-sdk/src/main/java/com/ably/tracking/ui/animation/CoreLocationAnimator.kt#L92) by the number of locations we have to animate and [update](https://github.com/ably/ably-asset-tracking-android/blob/main/ui-sdk/src/main/java/com/ably/tracking/ui/animation/CoreLocationAnimator.kt#L93) both the already added and the newly added animation steps to take an equal amount of time. Thanks to this we should not drift away from the current location because the individual animation steps are being sped up and slowed down, so the whole animation fits in the constant animation time.

So the key to not drifting away on Android is to modify the duration of animation steps. Does it also happen on iOS?

Now as I think about it, our approach isn't flawless because we can't modify the step that's currently being animated 🤔 For example, if we have a single animation step that takes 10 seconds, and then while it's animating we receive a new location update the second one will also take 10 seconds as the ongoing step is not on the animation steps list and we can't alter it. But even with that we should not be able to increase this drift endlessly, so it should be acceptable.

**Comment by lawrence-forooghian** [comment]
Yeah, on iOS the animation durations are calculated upfront - we never modify the duration of a step whose duration we've already calculated. I'm going to look into sorting this out.
