### ISSUE TITLE
Enable to add multiple trackables in the publisher example app

### ISSUE THREAD

**Issue by KacperKluka** [ably/ably-asset-tracking-swift#389]
The publisher can add multiple trackables which means it can track multiple assets at the same time. However, in the publisher example app, you can only add a single trackable. We should add support for adding multiple trackables, each should have its own ID, resolution settings, and destination. Feel free to check the Android app to see how this is handled in the UI.

┆Issue is synchronized with this [Jira Uncategorised](https://ably.atlassian.net/browse/SDK-2691) by [Unito](https://www.unito.io)

**Comment by arturjaworski** [comment]
Attaching Android example app screenshots

<img src="https://user-images.githubusercontent.com/1076431/194255524-bc9d1363-5a8f-4b3b-bc9a-3186e30d42e1.png" width="50%">
<img src="https://user-images.githubusercontent.com/1076431/194255551-48fef867-5b1c-4fc7-a29b-6e563affb12e.png" width="50%">

**Comment by lawrence-forooghian** [comment]
I think roughly the work will look something like this:

- Have a first page of the app which is the "Create publisher" page. Here you choose all the settings that are used to initialise the publisher (i.e. all of the `PublisherBuilder` methods). We might need to move some of these settings out of the current settings page. Then you press a "Create publisher" button which creates the global publisher.
- Move `Publisher` instance out of `MapViewModel` and into the top level of the app
- Probably want to globally store the last-received information for each trackable (e.g. connection state) so that we have it available when we navigate from the list screen to the map screen (instead of having to wait for another update)
- Create a list of trackables and update it in response to `didChangeTrackables` publisher delegate calls.
- Make this list the first view of the app, and put the existing trackable ID text field and button at the bottom. Change "Start publishing" to "Add", displaying an error if the publisher has not yet been started.
- Create link from trackable list to map screen, which displays (and updates in response to) last-received information for each trackable

I'd imagine the source of truth for all the data being at the list view level, and this data just then being passed in to the map view.

**Comment by lawrence-forooghian** [comment]
I started doing some work on this. Here's the UX that I've got in mind so far. It moves the creation of the publisher to its own screen at the beginning of the app, and puts all of the publisher initialisation-related settings there. Then after creating the publisher, you go to a "publisher details" view, which lists all of its trackables and has a button to add a new trackable.

The "add trackable" screen isn't built yet (it's just the first page of the current version of the app), but it'll let you set things like resolution, destination, etc.

The trackable list isn't working yet, but tapping on a trackable will let you view more details about it and see its position on a map, I think.

https://user-images.githubusercontent.com/53756884/195085056-162fb878-eacc-45c5-b425-bb4eb2a9425e.mov
