### ISSUE TITLE
Add the "Default resolution" section to the settings screen

### ISSUE THREAD

**Issue by KacperKluka** [ably/ably-asset-tracking-swift#390]
When adding multiple trackables it is helpful to be able to set default resolution values that will populate the UI when adding a trackable. Therefore, we should add a `Default resolution` section that allows specifying the accuracy, desired interval, and minimum displacement values. Those values should be then put in the UI fields when a user adds a trackable.

Connected to https://github.com/ably/ably-asset-tracking-swift/issues/389

┆Issue is synchronized with this [Jira Uncategorised](https://ably.atlassian.net/browse/SDK-2692) by [Unito](https://www.unito.io)

**Comment by arturjaworski** [comment]
Attaching Android example app screenshots

<img src="https://user-images.githubusercontent.com/1076431/194254780-f229d294-9ad5-4666-bda6-db342182a42f.png" width="50%">

**Comment by lawrence-forooghian** [comment]
@JakubJankowski I see that you've picked this one up. What's the UX that you've got in mind for this one, given that #389 (which I'm working on) is not yet implemented?

**Comment by lawrence-forooghian** [comment]
I think that (long-term, not sure what you're doing right now Jakub) the best place for this to go would be in a "Settings" tab, see below for a mockup of this on top of [my current work on #389](https://github.com/ably/ably-asset-tracking-swift/issues/389#issuecomment-1274577829):

https://user-images.githubusercontent.com/53756884/195086656-23f5ca0d-f0d5-44d9-b3f6-47397435a6da.mov

**Comment by JakubJankowski** [comment]
Sorry @lawrence-forooghian, I missed your comments and didn't realize we might be working on similar parts of the app.
I implemented it as a part of the current Settings screen, as an additional section at the top: https://github.com/ably/ably-asset-tracking-swift/pull/412
So I think we have a similar idea and it shouldn't be too difficult to integrate it move it into your solution, since the logic is very similar to the already existing Constant Resolution section in settings screen. Please let me know if you'd like me to do some changes though!

https://user-images.githubusercontent.com/15122679/195297309-514f60ae-a588-4d83-9847-9f92fb5c0e45.mov
