### ISSUE TITLE
Worker Queue: Legacy

### ISSUE THREAD

**Issue by AndyTWF** [ably/ably-asset-tracking-swift#569]
As part of the worker queue migration, we could adapt the current publishers do async work method to push that work onto the worker queue (a generic worker - takes a simple callback and runs it). That way we can confine all the async work to the queue, as we refactor out the workers.

Depends on the following work:

* https://github.com/ably/ably-asset-tracking-swift/issues/570

**Comment by lawrence-forooghian** [comment]
@AndyTWF To check I’ve understood – the idea here is to instantiate a worker queue inside `DefaultPublisher` and `DefaultSubscriber`, and to replace their `performOnWorking{Thread, Queue}` methods with a method that enqueues this generic function-calling worker, right?

**Comment by lawrence-forooghian** [comment]
Also, it says that it depends on #590, but that seems to be publisher specific whereas I assumed this one was about publisher and subscriber. I also don't think that we need the full properties types (i.e. #570) to be implemented in order to do this one – we just need empty placeholder properties types for publisher and subscriber, right?
